Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('posts.urls', namespace='posts')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='index'),
    url(r'^create/$', views.post_create, name='create'),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete),
]

posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone
from tinymce import HTMLField
from mptt.models import MPTTModel, TreeForeignKey


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


# def upload_location(instance, filename):
#     return f'{instance.slug}/{filename}'

def upload_location(instance, filename):
    return '{}/{}'.format(instance.slug, filename)


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=150)
    category = models.ForeignKey('Category', null=True, blank=True)
    description = models.TextField(max_length=250)
    content = HTMLField('Content')
    image = models.ImageField(null=True, blank=True,
                              width_field="width_field",
                              height_field="height_field",
                              upload_to=upload_location)
    width_field = models.IntegerField(default=0)
    height_field = models.IntegerField(default=0)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    slug = models.SlugField(unique=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    objects = PostManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-timestamp", "-updated"]


class Category(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    slug = models.SlugField()

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        unique_together = (('parent', 'slug',))
        verbose_name_plural = 'categories'

    def get_slug_list_for_categories(self):
        try:
            ancestors = self.get_ancestors(include_self=True)
        except:
            ancestors = []
        else:
            ancestors = [i.slug for i in ancestors]
        slugs = []
        for i in range(len(ancestors)):
            slugs.append('/'.join(ancestors[:i + 1]))

        return slugs

    def __str__(self):
        return self.name


# noinspection PyPackageRequirements
def create_slug(instance, new_slug=None):
    slug = slugify(instance)
    if new_slug:
        slug = new_slug
    qs = Post.objects.all().filter(slug=slug).order_by("-id")
    if qs.exists():
        slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from .models import Post
from tinymce import TinyMCE


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    publish = forms.DateField(widget=forms.SelectDateWidget)
    content = forms.CharField(widget=TinyMCEWidget(attrs={'required': False, 'cols': 30, 'rows': 10}))
    class Meta:
        model = Post
        fields = [
            'title',
            'author',
            'category',
            'description',
            'content',
            'image',
            'draft',
            'publish',
        ]

posts/views.py
from django.shortcuts import render, get_object_or_404
from urllib.parse import quote
from django.http import HttpResponseRedirect, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Category
from django.db.models import Q
from .forms import PostForm
from django.urls import reverse
from django.contrib import messages
from django.utils import timezone


def post_list(request):
    if not request.user.is_authenticated:
        all_posts = Post.objects.active()
    else:
        all_posts = Post.objects.all()
    query = request.GET.get('q')
    error_msg = ''
    if query:
        all_posts = all_posts.filter(
            Q(title__icontains = query)|
            Q(content__icontains=query) |
            Q(author__first_name__icontains=query) |
            Q(author__last_name__icontains=query)
            ).distinct()
        if len(all_posts) < 1:
            error_msg = "Sorry No Posts available for given query!"
    paginator = Paginator(all_posts, 2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'error_msg': error_msg,
    }
    return render(request, 'posts/post_list.html', context)


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if post.draft or post.publish > timezone.now().date():
        if not request.user.is_authenticated:
            raise Http404
    share_string = quote(post.content)
    context = {
        'post':post,
        'share_string':share_string,
    }
    return render(request, 'posts/detail.html', context)


def post_create(request):
    if not request.user.is_authenticated:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'Post added succesfully!')
        return HttpResponseRedirect(reverse('posts:index'))
    context = {
        'form': form,
        'status': 'Create'
    }
    return render(request, 'posts/form.html', context)


def post_update(request, slug):
    if not request.user.is_authenticated:
        raise Http404
    post = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        messages.success(request, 'Changes Saved!')
        return HttpResponseRedirect(reverse('posts:detail', args=(slug,)))
    context = {
        'form':form,
        'status': 'Edit'
    }
    return render(request, 'posts/form.html', context)


def post_delete(request, slug):
    if not request.user.is_authenticated:
        raise Http404
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        post.delete()
        messages.success(request, 'Successfully deleted!')
        return HttpResponseRedirect(reverse('posts:index'))
    context = {
        'post': post,
    }
    return render(request, 'posts/confirm_delete.html', context)


def show_category(request, hierarchy=None):
    category_slug = hierarchy.split('/')
    parent = None
    root = Category.objects.all()

    for slug in category_slug[:-1]:
        parent = root.get(parent=parent, slug = slug)

    try:
        instance = Category.objects.get(parent=parent, slug=category_slug[-1])
    except:
        instance = get_object_or_404(Post, slug = category_slug[-1])
        return render(request, "posts/detail.html", {'post': instance})
    else:
        return render(request, 'posts/categories.html', {'instance': instance})

posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block head_title %}FeedYourBrain{% endblock head_title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'posts/css/styles.css' %}"/>
    <link rel="stylesheet" href="{% static 'posts/css/default.css' %}"/>
    <link rel="stylesheet" href="{% static 'posts/css/font-style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="shortcut icon" type="image/svg" href="{% static 'favicon.svg' %}">
    {% block head_extra %}{% endblock head_extra %}
</head>
<body>
<div id="fb-root">
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</div>

<nav class="navbar navbar-expand-md fixed-top navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="/"><span class="h3">FeedYourBrain</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
            <li class="dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Category
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    {% for category in categories %}
                      <a class="dropdown-item text-white" href="/category/{{category.get_slug_list_for_categories |last}}">{{category.name}}</a>
                    {% endfor %}
                </div>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About<span class="sr-only">(current)</span></a>
          </li>

        </ul>
        <form class="form-inline my-2 my-lg-0" method="get" action="/">
            <div class="col-sm-10">
                <div class="input-group">
                  <input class="form-control mr-sm-0 border-right-0" type="text" name="q" placeholder="Search Posts" value="{{ request.GET.q }}" aria-label="Search" aria-describedby="basic-addon1">
                  <span class="input-group-addon fa fa-search bg-light border border-secondary" id="basic-addon1"></span>
              </div>
          </div>
        </form>
      </div>
  </div>
</nav>


<div class="container pt-5 mt-4">
        {% include 'posts/messages.html' %}
        {% block content %}
        {% endblock content %}
</div>
<footer class="footer">
  <div class="row align-items-center w-100 h-100">
    <div class="col-lg-4 col-md-6 col-sm-6 mx-auto">
      <div class="d-flex justify-content-around pl-4">
        <i class="fa fa-github fa-2x icon-3d"></i>
        <i class="fa fa-twitter fa-2x icon-3d"></i>
        <i class="fa fa-facebook fa-2x icon-3d"></i>
        <i class="fa fa-instagram fa-2x icon-3d"></i>
      </div>
    </div>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

<script src="{% static 'posts/css/highlight.pack.js' %}"></script>
<script>hljs.initHighlightingOnLoad();</script>
<script type="text/javascript">
  $(document).ready(function(){
    $(".img-content img").each(function(){
      $(this).addClass("img-responsive")
       $(this).removeAttr("width")
       $(this).removeAttr("height")

    })
  })
</script>
</body>
</html>
 

posts/templates/posts/categories.html
{% extends 'posts/base.html' %}
{% load static  %}
{% load namify %}
{% block head_title %} {{ instance.name }} {% endblock %}

{% block content %}
<br>
<ol class="breadcrumb">
  <li class="breadcrumb-item green-color"><a class="green-color" href="/">Home</a></li>
    {% for i in instance.get_slug_list_for_categories %}
       <li class="breadcrumb-item"><a class="green-color" href="/category/{{ i }}">{{ i | get_name |capfirst }}</a></li>
    {% endfor %}
</ol>

{% if  instance.children.all %}
    <h4 class="pb-2">Sub Categories</h4>
    <div class="row">
    {% for i in instance.children.all %}
        <div class="col-md-4">
            <div class="card mb-2">
              <div class="card-body">
                  <a class="green-color" href="{{ i.slug }}">{{ i.name }}</a>
              </div>
            </div>
        </div>
    {% endfor %}
    </div>
    <br><hr>
{% endif %}

{% if  instance.post_set.all %}

<div class="row">
 {% for post in instance.post_set.all %}
    <div class="col-lg-4 col-md-6">
        <div class="card shadow mb-3">
            <a class="text-dark" href="{{ post.slug }}">
            <div class="card-body">
                <h4 class="card-title">{{ post.title| truncatechars:50 }}</h4>
                {% if post.image %}
                    <img class="card-img-top img-responsive mb-1" src="{{post.image.url}}" alt="Card image cap">
                {% endif %}
                <p class="card-text text-justify">{{ post.description }}</p>
            </div>
            </a>
        </div>
    </div>
 {% endfor %}
</div>
{% endif %}

{% endblock %}

posts/templates/posts/confirm_delete.html
{% extends 'posts/base.html' %}

{% block head_title %}
    Delete Post | Try Django 1.9
{% endblock head_title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p class="h1">Are you sure you want to delete "{{ post }}" ?</p>
        <input type="submit" value="Confirm" class="danger btn btn-danger active text-white mt-3">
        <a class="btn btn-default text-white mt-3 ml-3" style="color:black" href="{% url 'posts:index' %}">Cancel</a>
    </form>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'posts/base.html' %}
{% load namify %}
{% block head_title %}
    {{post.title}} | Try Django 1.9
{% endblock head_title %}

{% block content %}
<ol class="breadcrumb">
  <li class="breadcrumb-item green-color"><a class="green-color" href="/">Home</a></li>
    {% for i in post.category.get_slug_list_for_categories %}
       <li class="breadcrumb-item"><a class="green-color" href="/category/{{ i }}">{{ i | get_name |capfirst }}</a></li>
    {% endfor %}
</ol>
<div class="row">
    <div class="col-md-8">
        <h1>{{ post.title }}</h1>
        <p><small>--By: {{ post.author.get_full_name }}</small></p>
        <small class="text-muted"><i class="fa fa-calendar ml-1 mr-1" aria-hidden="true"></i>{{ post.publish }}</small>

        {% if post.draft %}
            <span style="color:red">Draft</span>
        {% endif %}
        {% if post.image %}
            <img class="card-img-top img-responsive p-1" src="{{post.image.url}}" alt="Card image cap">
        {% endif %}
        <hr>
        <div class="img-content">{{ post.content| safe }}</div>
        <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
        <hr>
        <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-width="740" data-numposts="5"></div>
    </div>
</div>
{% endblock content %}

posts/templates/posts/form.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ status }} | Try Django 1.9
{% endblock head_title %}
{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}
{% block content %}
    <form class="mb-5" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn text-white" type="submit" value="{{ status }} Post">
    </form>
{% endblock content %}

posts/templates/posts/messages.html
{% if messages %}
<div class="messages">
    <div class="messages">
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
	        <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
	        {% endfor %}
        </div>
    </div>
</div>
{% endif %}

posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}
{% block content %}
{% if error_msg %}
<div class="row justify-content-center">
  <div class="display-4 pb-5 pt-5">
    {{error_msg}}
  </div>
</div>
{% endif %}
{% if posts %}
    {% for post in posts %}
    <div class="row justify-content-center px-2 mb-3">
    <div class="card shadow" style="width: 50rem;">
        <div class="card-body">
        <p class="card-title text-center pb-1 h2 card-heading"><a id="heading" href="{% url 'posts:detail' slug=post.slug %}">{{ post.title }}</a></p>
            <div class="text-center mb-2"><small class="text-muted mr-3"><i class="fa fa-calendar ml-1 mr-1" aria-hidden="true"></i>{{post.publish}}</small><small class="text-muted ml-3"><i class="fa fa-pencil mr-1" aria-hidden="true"></i>{{ post.author.get_full_name }}</small></div>
        {% if post.image %}
            <img class="card-img-top img-responsive" src="{{post.image.url}}" alt="Card image cap">
        {% endif %}
        <div class="card-text p-2 text-justify img-content">{{ post.description }}</div>
        <a href="{% url 'posts:detail' slug=post.slug %}" class="btn btn-block text-white">Read More</a>
      </div>
    </div>
    </div>
    {% endfor %}
    <div class="row justify-content-center">
        <div class="row">
            <nav aria-label="Page navigation example">
                  <ul class="pagination">
                    <li class="page-item">
                        {% if posts.has_previous %}
                                    <a class="page-link text-dark" href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a>
                        </a></li>
                        {% else %}
                            <li class="page-item disabled">
                                  <span style="border-top-left-radius: 5px;border-bottom-left-radius: 5px;" class="page-link">&laquo;</span>
                            </li>
                        {% endif %}

                        {% for page_no in posts.paginator.page_range %}
                          {% if page_no == posts.number %}
                            <li class="page-item"><a class="page-link pg-active" href="?page={{page_no}}">{{page_no}}</a></li>
                          {% else %}
                            <li class="page-item"><a class="page-link text-dark" href="?page={{page_no}}">{{page_no}}</a></li>
                          {% endif %}
                        {% endfor %}
                  
                    <li class="page-item">
                        {% if posts.has_next %}
                                    <a class="page-link text-dark" href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo;</a>
                        </li>
                      {% else %}
                            <li class="page-item disabled">
                                  <span class="page-link">&raquo;</span>
                            </li>
                      {% endif %}
                  </ul>
            </nav>

        </div>
        <br/>

    </div>
    <br/>
{% endif %}
{% endblock content %}